// <auto-generated />
using Exercise1.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercise1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250224205752_deleted_all_the_migrations")]
    partial class deleted_all_the_migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Exercise1.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Name = "London"
                        });
                });

            modelBuilder.Entity("Exercise1.Models.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Atvars Apenes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Violetta Viktoriia Nguyen"
                        });
                });

            modelBuilder.Entity("Exercise1.Models.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PassportNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Passports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PassportNumber = "123456"
                        },
                        new
                        {
                            Id = 2,
                            PassportNumber = "654321"
                        });
                });

            modelBuilder.Entity("Exercise1.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuideId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuideId = 1,
                            Title = "Paris Tour"
                        },
                        new
                        {
                            Id = 2,
                            GuideId = 2,
                            Title = "London Tour"
                        },
                        new
                        {
                            Id = 3,
                            GuideId = 2,
                            Title = "Paris Tour"
                        });
                });

            modelBuilder.Entity("Exercise1.Models.Traveller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<int>("PassportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassportId")
                        .IsUnique();

                    b.ToTable("Travellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe",
                            PassportId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Jane Doe",
                            PassportId = 2
                        });
                });

            modelBuilder.Entity("Exercise1.Models.TravellerDestination", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TravellerId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "TravellerId");

                    b.HasIndex("TravellerId");

                    b.ToTable("TravellerDestination");
                });

            modelBuilder.Entity("Exercise1.Models.Tour", b =>
                {
                    b.HasOne("Exercise1.Models.Guide", "Guide")
                        .WithMany("Tours")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("Exercise1.Models.Traveller", b =>
                {
                    b.HasOne("Exercise1.Models.Passport", "Passport")
                        .WithOne("Traveller")
                        .HasForeignKey("Exercise1.Models.Traveller", "PassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("Exercise1.Models.TravellerDestination", b =>
                {
                    b.HasOne("Exercise1.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercise1.Models.Traveller", null)
                        .WithMany()
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exercise1.Models.Guide", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Exercise1.Models.Passport", b =>
                {
                    b.Navigation("Traveller");
                });
#pragma warning restore 612, 618
        }
    }
}
