@url = http://localhost:5260

### GET all cars
GET {{url}}/cars

### POST a new car
POST {{url}}/cars
Content-Type: application/json

{
    "Brand": "Toyota",
    "Model": "Corolla",
    "Plate": "ABC-123",
    "Color": "Red"
}

### GET all registrations

GET {{url}}/registrations


### POST a new registration

POST {{url}}/registrations
Content-Type: application/json

{
    "start": "2025-03-24",
    "carId": 5
}

### PUT registration
PUT {{url}}/registrations/8