@url = http://localhost:5083
@apikey = secret key

### Seed data
GET {{url}}/seed

### GET all brands

GET {{url}}/brands
XApiKey: {{apikey}}

### GET all occasions

GET {{url}}/occasions

### GET all sneakers

GET {{url}}/sneakers

### POST new sneaker
POST {{url}}/sneakers
XApiKey: {{apikey}}
Content-Type: application/json

{
    "name": "Nike Air Max 90",
    "price": 120,
    "stock": 10,
    "brand": {
        "brandId": "67e2a9c1fb5dc482d6f9240d",
        "name": "PUMA"
    },
    "occasions": [
      {
        "occasionId": "67e2a9c1fb5dc482d6f9240e",
        "description": "Sports"
      },
      {
        "occasionId": "67e2a9c1fb5dc482d6f9240f",
        "description": "Casual"
      }
    ]
    
}

### GET all sneakers with correct API key
GET {{url}}/sneakers
XApiKey: {{apikey}}

### GET sneaker by ID
GET {{url}}/sneakers/67e2a9c1fb5dc482d6f92412
XApiKey: {{apikey}}

### POST new User

POST {{url}}/users
XApiKey: {{apikey}}
Content-Type: application/json

{
  "customerNr": "K0002",
  "discount": 10,
  "apiKey": "API-KEY-4321"
}

### GET sneakers with custom API key for user K0001
GET {{url}}/sneakers
XApiKey: API-KEY-1234

### GET sneakers with custom API key for user K0002
GET {{url}}/sneakers
XApiKey: API-KEY-4321